shortcuts:
    start: [Enter, Space]
    pause: [Enter, Space]
    resume: [Enter, Space]
    reset: [Ctrl+R]
    restart: [Ctrl+Shift+R]
    clear: [Ctrl+Backspace, Ctrl+Delete]
    step: [Ctrl+Right, Ctrl+., Tab]

    resize: [G]
    generate_noise: [N]

    undo: [Ctrl+Z]
    redo: [Ctrl+Y, Ctrl+Shift+Z]
    save_as_new: [Ctrl+Shift+S]
    new: [Ctrl+N]
    save: [Ctrl+S]
    load: [Ctrl+O]
    close: [Ctrl+W]

    deselect: [Esc]
    select_all: [Ctrl+A]
    delete: [Backspace, Delete]
    copy: [Ctrl+C]
    cut: [Ctrl+X]
    paste: [Ctrl+V]
    rotate_clockwise: [R]
    rotate_counterclockwise: [Shift+R]
    flip_horizontal: [Ctrl+K]
    flip_vertical: [Ctrl+L]

    nudge_left: [Left, Shift+Left]
    nudge_right: [Right, Shift+Right]
    nudge_up: [Up, Shift+Up]
    nudge_down: [Down, Shift+Down]