name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang-format

    - name: Run Formatting
      run: |
        cmake -DPROJECT_SOURCE_DIR="${{ github.workspace }}" -P cmake/RunFormat.cmake
        git diff --exit-code

  build:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++-14 libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev libglu1-mesa-dev pkg-config libgtk-3-dev
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-14 100

    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install ninja llvm@18
        echo "CXX=$(brew --prefix llvm@18)/bin/clang++" >> $GITHUB_ENV
        echo "CC=$(brew --prefix llvm@18)/bin/clang" >> $GITHUB_ENV

    - name: Install Dependencies (Windows)
      if: runner.os == 'Windows'
      run: choco install ninja

    - name: Setup MSVC Developer Command Prompt (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --parallel

    - name: Test
      run: ctest --test-dir build --build-config Release --output-on-failure --parallel
