name: Release

on:
  workflow_run:
    workflows: ["Build & Test"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    name: Package (${{ matrix.name }})
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-gcc
          - os: windows-latest
            name: windows-msvc
          - os: macos-latest
            name: macos-clang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packaging Utilities (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm binutils cmake ninja-build

      - name: Install WiX (Windows)
        if: runner.os == 'Windows'
        run: | 
          dotnet tool install --global wix
          wix eula accept wix7
          wix extension add -g WixToolset.UI.wixext

      - name: Fetch Artifacts
        if: runner.os != 'macOS'
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.name }}
          path: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch x86_64 Artifacts (macOS)
        if: runner.os == 'macOS'
        uses: actions/download-artifact@v4
        with:
          name: build-macos-x86_64-clang
          path: build-x86_64
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch arm64 Artifacts (macOS)
        if: runner.os == 'macOS'
        uses: actions/download-artifact@v4
        with:
          name: build-macos-arm64-clang
          path: build-arm64
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Generate
        if: runner.os != 'macOS'
        working-directory: build
        run: cpack -C Release

      - name: Generate (macOS)
        if: runner.os == 'macOS'
        run: |
          X86_APP_BIN="build-x86_64/GOLExecutable/GOLDE.app/Contents/MacOS/GOLDE"
          ARM_APP_BIN="build-arm64/GOLExecutable/GOLDE.app/Contents/MacOS/GOLDE"

          lipo -create "$X86_APP_BIN" "$ARM_APP_BIN" -output "$ARM_APP_BIN"

          # Debugging
          chmod +x "$ARM_APP_BIN"
          lipo -info "$ARM_APP_BIN"

          mv build-arm64 build
          cd build
          cpack -C Release

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          TAG_NAME="${{ github.event.workflow_run.head_branch }}"

          gh release create $TAG_NAME \
          --title "Release $TAG_NAME" \
          --generate-notes \
          --draft \
          2>/dev/null

          cd build
          for file in *.msi *.zip *.dmg *.tar.gz *.deb *.rpm; do
              if [ -f "$file" ]; then
              echo "Uploading $file to Release..."
              gh release upload $TAG_NAME "$file" --clobber
              fi
          done
    
      - name: Upload WiX Logs on Failure
        if: failure() && matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: wix-error-logs-${{ matrix.name }}
          path: |
            build/_CPack_Packages/win64/WIX/wix.log
            build/_CPack_Packages/win64/WIX/**/*.wxs
          if-no-files-found: warn