name: Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      # This is often needed when using the Ninja generator on Windows to ensure CMake finds the MSVC compiler (cl.exe).

    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Check Formatting
      run: |
        cmake --build build --target Format
        git diff --exit-code

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build --build-config Release --output-on-failure
